### ISSUE TITLE
Dependency version requirements for this library

### ISSUE THREAD

**Issue by YeFei572** [m-r-davari/flutter_3d_controller#35]
Because the version of Flutter is too low, it is recommended to minimize the dependency version of some plugins to facilitate the use of users who have not upgraded Flutter.

```yaml
dependency_overrides:
  path:
    version: 1.8.3
  http:
    version: 1.2.0
  webview_flutter:
    version: 4.5.0
  webview_flutter_wkwebview:
    version: 3.10.2
```
