### ISSUE TITLE
Cannot build to run on web

### ISSUE THREAD

**Issue by mxg-mega** [m-r-davari/flutter_3d_controller#58]
I tried to run to continue developing my app after adding the package, updating the index.html file and the android manifest, but it keeps showing me this error:

```
Launching lib\main.dart on Chrome in debug mode...
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/utils/extensions.dart:5:25: Error: The getter 'a' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'a'.
    return _floatToInt8(a) << 24 |
                        ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/utils/extensions.dart:6:22: Error: The getter 'r' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'r'.
        _floatToInt8(r) << 16 |
                     ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/utils/extensions.dart:7:22: Error: The getter 'g' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'g'.
        _floatToInt8(g) << 8 |
                     ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/utils/extensions.dart:8:22: Error: The getter 'b' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'b'.
        _floatToInt8(b) << 0;
                     ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/obj_viewer/material.dart:236:24: Error: The getter 'r' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'r'.
  return Vector3(color.r / 255, color.g / 255, color.b / 255);
                       ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/obj_viewer/material.dart:236:39: Error: The getter 'g' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'g'.
  return Vector3(color.r / 255, color.g / 255, color.b / 255);
                                      ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/obj_viewer/material.dart:236:54: Error: The getter 'b' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'b'.
  return Vector3(color.r / 255, color.g / 255, color.b / 255);
                                                     ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:353:51: Error: The getter 'r' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'r'.
        'background-color: rgba(${backgroundColor.r * 255}, ${backgroundColor.g * 255}, ${backgroundColor.b * 255}, ${backgroundColor.a * 255}); ',
                                                  ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:353:79: Error: The getter 'g' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'g'.
        'background-color: rgba(${backgroundColor.r * 255}, ${backgroundColor.g * 255}, ${backgroundColor.b * 255}, ${backgroundColor.a * 255}); ',
                                                                              ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:353:107: Error: The getter 'b' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'b'.
        'background-color: rgba(${backgroundColor.r * 255}, ${backgroundColor.g * 255}, ${backgroundColor.b * 255}, ${backgroundColor.a * 255}); ',
                                                                                          ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:353:135: Error: The getter 'a' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'a'.
        'background-color: rgba(${backgroundColor.r * 255}, ${backgroundColor.g * 255}, ${backgroundColor.b * 255}, ${backgroundColor.a * 255}); ',
                                                                                          ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:359:59: Error: The getter 'r' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'r'.
          ' --progress-bar-color: rgba(${progressBarColor.r * 255}, ${progressBarColor.g * 255}, ${progressBarColor.b * 255}, ${progressBarColor.a * 255})');
                                                          ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:359:88: Error: The getter 'g' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'g'.
          ' --progress-bar-color: rgba(${progressBarColor.r * 255}, ${progressBarColor.g * 255}, ${progressBarColor.b * 255}, ${progressBarColor.a * 255})');
                                                                                       ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:359:117: Error: The getter 'b' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'b'.
          ' --progress-bar-color: rgba(${progressBarColor.r * 255}, ${progressBarColor.g * 255}, ${progressBarColor.b * 255}, ${progressBarColor.a * 255})');
                                                                                          ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_3d_controller-2.1.0/lib/src/core/modules/model_viewer/html_builder.dart:359:146: Error: The getter 'a' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'a'.
          ' --progress-bar-color: rgba(${progressBarColor.r * 255}, ${progressBarColor.g * 255}, ${progressBarColor.b * 255}, ${progressBarColor.a * 255})');
                                                                                          ^
Failed to compile application.

Exited (1).
```
i do not know why this is happening. here is my pubspec.yaml :
```
name: avatar_duet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  model_viewer_plus: 
  nice_buttons: ^0.0.3
  provider: ^6.1.2
  flutter_3d_controller: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/models/
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
```

I would really appreciate if there is a fix for this. Thank you.
